### ISSUE TITLE
music controls are not shown when using cordova-plugin-playlist plugin

### ISSUE THREAD

**Issue by alexwang2013** [Rolamix/cordova-plugin-playlist#35]
### Expected Behaviour
music controls are shown to control start, stop, next and previous of the songs.

### Actual Behaviour
music controls are not shown

### Reproduce Scenario (including but not limited to)
play a mp4 music, then the music is playing at background, without controls displaying.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)
ios 12.4.1

#### Cordova CLI version and cordova platform version

    cordova --version                                    7.1.0
    cordova platform version ios                    ios 4.5.5

#### Plugin version

    cordova plugin version | grep phonegap-plugin-push   # e.g. 1.5.3

**Comment by the-hip-group** [comment]
@alexwang2013 Why did you close this? Were you able to find a solution? I am having similar issues where the audio controls do not show up.
