### ISSUE TITLE
iPhone audio playback is very quiet on the handset speakers; seems to be playing through the wrong speaker

### ISSUE THREAD

**Issue by robincsmith** [Rolamix/cordova-plugin-playlist#6]
### Expected Behaviour

iPhone playback should be through the default audio speaker at a 'normal' volume by default, when no devices are connected to the handset

### Actual Behaviour

Playback is extremely quiet, and seems to be playing through the earpiece

### Reproduce Scenario (including but not limited to)

iOS with Ionic, listening to tracks from various sources

#### Steps to Reproduce

Play any kind of track on iPhone, without any devices (e.g. headphones, speakers) connected

#### Platform and Version

iOS 11.4

#### Cordova CLI version and cordova platform version

Cordova CLI version 7.1.0

**Comment by codinronan** [comment]
And again #7  :)
